# Generated by Django 4.0 on 2022-02-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cardnum', models.IntegerField()),
                ('Date', models.DateField()),
                ('Merchnum', models.CharField(max_length=20)),
                ('Merch_description', models.CharField(max_length=100)),
                ('Merch_state', models.CharField(max_length=10)),
                ('Merch_id', models.IntegerField()),
                ('Transtype', models.CharField(max_length=1)),
                ('Amount', models.FloatField()),
            ],
        ),
    ]
