# Generated by Django 4.0 on 2022-02-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='Merch_id',
            new_name='Merch_zip',
        ),
    ]
